.travis.yml
Gemfile
Rakefile
lib/chef_zero/data_store/memory_store_v2.rb
lib/chef_zero/data_store/v1_to_v2_adapter.rb
lib/chef_zero/endpoints/policies_endpoint.rb
lib/chef_zero/server.rb
spec/run_oc_pedant.rb
spec/run_pedant.rb
spec/support/pedant.rb

Implements the Policyfile API first iteration, corresponding to https://github.com/opscode/chef-pedant/pull/90 This API is likely to be revised; An RFC describing the final API will be proposed soon, and chef-zero will be updated accordingly then. In the interim this feature should be safe to merge since it's gated by two feature flags on the client side (and warnings about instability are emitted by both ChefDK and Chef Client when using it).

Policyfile get/set API

---

Gemfile
lib/chef_zero/endpoints/policies_endpoint.rb

In the Policyfile draft RFC, `revision_id` is a required field. Add this validation to Chef Zero. This works locally with changes to pedant, but I can't commit those because erchef's policyfile validation is broken.
* ChefDK PR: https://github.com/chef/chef-dk/pull/323
* Pedant: https://github.com/chef/chef-pedant/pull/100
* Policyfile Draft RFC: https://github.com/chef/chef-rfc/pull/91

Policyfile Revision ID Validation.

---

lib/chef_zero/server.rb

Currently, mounting the /users endpoint at the top level when in
osc_compat mode causes errrors in the Chef integration tests. This may
be due to a misconfiguration in the way Chef implements local mode but I
am unable to pinpoint the exact causes right now. In any case, this is
the minimal "revert" of 1b2a6e5f107254cce8200a4750035b30265ae0c8 that
gets Chef's integration tests working again.
@jkeiser @chef/client-core

Partially Revert 1b2a6e5f107254cce8200a4750035b30265ae0c8

---

lib/chef_zero/rest_base.rb
lib/chef_zero/server.rb
lib/chef_zero/socketless_server_map.rb
spec/socketless_server_map_spec.rb

Allows Chef local mode to hit Chef Zero directly in-memory with no networking involved.
Note this branch includes https://github.com/chef/chef-zero/pull/120 which is what I needed to do to get the Chef integration tests passing for now, but if there's a better solution to that problem I'm more than happy to cherry-pick. Also I need to move the SocketlessServerMap to its own file, but some folks said they would try this code soon so I wanted to make it available.
@chef/client-core @jkeiser

Socketless Requests

---

chef-zero.gemspec

same change as chef and ohai, same rationale for not bumping the
lower bound to 2.0

bump ffi-yajl dep

---

lib/chef_zero/rspec.rb

This fixes an error where server configs are persisted between tests, so the last configuration set wins.

Don't pollute global Chef server options

---

CHANGELOG.md
lib/chef_zero/socketless_server_map.rb
spec/socketless_server_map_spec.rb

To help with https://github.com/chef/chef-provisioning/pull/337
\cc @jkeiser @danielsdeleo

Adding `server_on_port` method to socketless server map

---

lib/chef_zero/rspec.rb

This fixes IPv6 integration tests in Chef for me
@chef/client-core

Access server opts in example context not describe context

---

Gemfile
chef-zero.gemspec
gemfiles/latest-chef.gemfile
gemfiles/oc-chef-pedant.gemfile
lib/chef_zero/endpoints/organization_association_requests_endpoint.rb
lib/chef_zero/endpoints/organization_user_base.rb
lib/chef_zero/endpoints/organization_users_endpoint.rb
lib/chef_zero/version.rb

This commit simply updates the dependencies for more recent versions.

Update gem dependencies

---

Gemfile
spec/run_oc_pedant.rb

Use the embedded pedant in the chef-server repo.  This also requires
slight changes to the pedant configuration, as the options have changed.

Switch to pedant in chef-server repo

---

lib/chef_zero/endpoints/organization_association_requests_endpoint.rb
lib/chef_zero/endpoints/organization_user_base.rb
lib/chef_zero/endpoints/organization_users_endpoint.rb

I think we over-simplified in https://github.com/chef/chef-zero/pull/146 - adding a user to an org was no longer removing the association request or adding the user to the groups.  I _think_ I have fixed this now.
The only reason I caught this was the failures coming from https://github.com/chef/cheffish/blob/17638eec1cee1efd1cd68e4c531d984b5201c214/spec/integration/chef_organization_spec.rb#L145-L153 - cheffish was testing to make sure chef-zero was removing the user from the association when it was added to the org.  There was no failing pedant test for this - I need to file a oc-chef-pedant issue to get this covered.
\cc @jkeiser @ssd @marcparadise @andrewjamesbrown

Adding back logic to delete the association request when adding a user to an org (as well as adding the user to the groups)

---

lib/chef_zero/endpoints/policies_endpoint.rb
spec/server_spec.rb

I am updating chef-zero in Debian, and when building the package in a clean environment (with no chef, and only the dependencies that are declared in the gemspec installed), tests fail. This PR has two commits that fix the issue for me.

Remove dependency on chef

---

Gemfile
Rakefile
lib/chef_zero/chef_data/default_creator.rb
lib/chef_zero/endpoints/principal_endpoint.rb
lib/chef_zero/server.rb
spec/run_oc_pedant.rb
spec/support/oc_pedant.rb

This has `chef-zero` run against the most recent version of `oc-chef-pedant` (currently 2.2.0, though we'll need to do a release due to a single change there), and has numerous changes to run with ChefFS as the backing store.
Depends on:
- https://github.com/chef/chef-server/pull/622 (`oc-chef-pedant` tags and behavioral changes)
- https://github.com/chef/chef/pull/4173 (ChefFS changes to handle invitations and members)

Upgrade pedant, and enable running in ChefFS mode

---

Gemfile
spec/run_oc_pedant.rb

chef/chef-server#645 implements the universe endpoint in chef-server. I can't really see any reason that you'd need or want a universe endpoint in zero, since it's mostly to allow berkshelf or Policyfiles to resolve the set of available cookbooks. 
This branch ignores the universe endpoint tests, and currently points at the branch in chef-server that implements them. That'll need to get updated before merge.

Ignore the universe endpoint tests in pedant

---

spec/run_oc_pedant.rb

This translates to excluding tests that are tagged `:internal_orgs`, but there aren't any such tests any more.

Internal orgs appears to be unused in oc-chef-pedant

---

lib/chef_zero/endpoints/cookbook_artifact_endpoint.rb
lib/chef_zero/endpoints/cookbook_artifact_identifier_endpoint.rb
lib/chef_zero/endpoints/cookbook_artifacts_cookbook_identifier.rb
lib/chef_zero/endpoints/cookbook_version_endpoint.rb
lib/chef_zero/server.rb

- Right now, there are multiple calls to hoover_delete_checksums but we only override one of them.
- This patch also fixes the spot where we delete /cookbook_artifacts/name when the last /cookbook_artifacts/name/identifier is removed.

Make hoovering and deleting parent dir work everywhere for cookbook_artifacts

---

spec/run_oc_pedant.rb

Pedant only has 2 tests for this, one of which was a validation test that wasn't tagged w/ validation. I fixed that in https://github.com/chef/chef-server/pull/703 The other test was already passing.

Enable headers pedant tests

---

lib/chef_zero/chef_data/cookbook_data.rb

there's a Kernel#gem method in ruby because someone thought that would
be a great idea, kind of messes up method_missing when the method isn't
missing...

fix necessary for metadata gem

---

Rakefile
lib/chef_zero/chef_data/data_normalizer.rb
lib/chef_zero/data_store/data_error.rb
lib/chef_zero/endpoints/actor_default_key_endpoint.rb
lib/chef_zero/endpoints/actor_endpoint.rb
lib/chef_zero/endpoints/actor_key_endpoint.rb
lib/chef_zero/endpoints/actor_keys_endpoint.rb
lib/chef_zero/endpoints/rest_object_endpoint.rb
lib/chef_zero/endpoints/server_api_version_endpoint.rb
lib/chef_zero/rest_base.rb
lib/chef_zero/rest_error_response.rb
lib/chef_zero/rest_router.rb
lib/chef_zero/rspec.rb
lib/chef_zero/server.rb
spec/run_oc_pedant.rb

Depends on chef/chef#4587 and chef/chef-server#740.
- Implement ActorKeyEndpoint, ActorDefaultKeyEndpoint, ActorKeysEndpoint.
- Implement user, client keys in `ActorEndpoint#delete`, `#put`.
- RestBase
- Fix RestErrorResponse exceptions to report actual `rest_path`
instead associated with the failed data store operation instead of
`request.rest_path`.
- Move `json_response`, `already_json_response` args `request_version`
and `response_version` into options hash; add docs.
- DataError, RestErrorResponse: Pass useful message text to `super`.
- RestRouter: Clean up logging
- Print request methods, paths and bodies more readably for log_level >= INFO.
- Pretty-print RestRequest objects (only printed when log_level == DEBUG).
- Server: Change default log_level to `:warn` (to enable logging …

Make user and client keys endpoints pass Pedant specs

---

.travis.yml
chef-zero.gemspec
lib/chef_zero/server.rb

[options[:port]].flatten does not do the right thing in the case that options[:port] is an Enumerator.
options[:host] is not always an Array (can be a String).

Fix bugs related to Array vs Enumerator vs Port for options[:port/host].

---

lib/chef_zero/rest_router.rb

Logging these at info means that when a user runs:
chef-client -z
They may get all of their cookbook content logged to their terminal
(depending out their outputting options).  Since INFO is the default 
log_level for non-tty devices, this has a big impact on what people 
might see in their system log files or CI systems.

Log responses only at debug log level

---

chef-zero.gemspec

Rack 2.0.1 was just released and it requires Ruby 2.2+

Depend on rack < 2 to restore Ruby 2.1 compat

---

lib/chef_zero/rest_router.rb

We upgraded to chef-zero 4.7.0, and users have been confused by all the POST/PUT messages on the console. It makes it look like we're sending sensitive information to our servers.
Closes #215

Downgrade info log message to debug

---

lib/chef_zero/server.rb

Set flags to disable unsecure ssl options.
I have referenced this flags from [Changed default settings of ext/openssl](https://www.ruby-lang.org/en/news/2014/10/27/changing-default-settings-of-ext-openssl/ "Changed default settings of ext/openssl").

disable sslv3 and few unsecure options

---

lib/chef_zero/rest_request.rb

We have some complex reasons to hide a ChefZero behind an SSL nginx proxy.
One problem that suddenly arose with this is that URLs returned by
posting to /environment/foo/cookbook_versions use the protocol of the
internal webrick which is always plain http. This causes the chef client
to retrieve these urls on the https port but with an encrypted payload.
Support this situation by using the HTTP_X_FORWARDED_PROTO CGI variable
if it is available.

Make ChefZero aware of load balancers

---

lib/chef_zero/chef_data/data_normalizer.rb

normal has `tags` attributes with empty array. so let data_normalizer has it.
P.S. this fix in cooperation with @sawanoboly .

add normal tags with empty array

---

bin/chef-zero

When running chef-zero with the daemon option on Windows, the error message incorrectly says 'Process.daemon requires Ruby >= 1.9', even when Windows has Ruby 2.0+.

Update error message for daemon on Windows

---

lib/chef_zero/solr/query/regexpable_query.rb

Currently, dash character is defined as non-word character and it results into following search oddities:
```
$ knife node create mysql -d -z
Created node[mysql]
$ knife node create mysql-slave -d -z
Created node[mysql-slave]
$ knife search node 'name:mysql' -a name -z
2 items found
mysql:
name: mysql
mysql-slave:
name: mysql-slave
$ knife search node 'name:mysql?slave' -a name -z
0 items found
$ knife search node 'name:mysql-?lave' -a name -z
1 items found
mysql-slave:
name: mysql-slave
```

Fix scary search behavior on terms containing dash character

---

lib/chef_zero/chef_data/cookbook_data.rb

most of our metadata is the form of:
key "value"
but chef_version can be:
chef_version ">= 12.3.1", "< 13.0.0"
so we need a splat in method messing and need to shovel it into an
array.
relates to chef/chef#4081

add patch to support chef_version

---

lib/chef_zero/rest_base.rb

If file name includes URL meta characters, knife can't get that file.
So I add URI escape and decode for URI.

support URI specific character in file name

---

lib/chef_zero/rest_base.rb

This fixes the problem at the beginning of chef-zero run:
```
[2016-07-06T23:11:17+00:00] INFO: #<ChefZero::RestErrorResponse: 404: Object not found: chefzero://localhost:8889/nodes/vagrant-ubuntu-trusty-64>
```
It doesn't influence the run but it confuses the users as it looks like a failure.

Set log level to debug in the rescue block.

---

lib/chef_zero/endpoints/search_endpoint.rb
lib/chef_zero/solr/solr_parser.rb

Previously, chef-zero would return an HTTP 500 Internal Server Error
when the Solr parser failed.  Now, we return HTTP 400 with an error
message identical to that of the Erchef server. Returning HTTP 400
also improves the end-user experience since knife returns more
sensible error messages.
Before this patch:
> knife search nodes 'recipes:bar::bar'
ERROR: Server returned error 500 for http://127.0.0.1:8889/search...
After:
> knife search nodes 'recipes:bar::bar'
ERROR: knife search failed: invalid search query: 'recipes:bar::bar'
closes #101

Return HTTP 400 Bad Request on Solr parse error

---

lib/chef_zero/chef_data/data_normalizer.rb
lib/chef_zero/version.rb

This brings pedant up to date with changes to the ACLs endpoiint that are currently in flight.   When 'clients' and 'users' are included in an ACL PUT, that is combined to form the list of actors.

Support clients and users fields in ACL PUT requests

---

lib/chef_zero/chef_data/data_normalizer.rb
lib/chef_zero/chef_data/default_creator.rb
lib/chef_zero/endpoints/acls_endpoint.rb

Chef Server has the ability to return users and clients separately
within an GET ACL request when `detail=granular`.  To support that,
we need to store them separately and determine if we want to present
`actors` or `users` and `clients` at the time of the request.
This change makes a reasonable best effort at capturing the creator
type (user v client) correctly and uses that for determining its
assignment in acls.

store ACEs by client/user

---

Gemfile
lib/chef_zero/endpoints/search_endpoint.rb

Chef Zero would, on a search request using the "start" or "rows"
parameters, always return all rows.
This change makes it so only the correct number of rows are returned or
the results start at the correct index.
This change will make the tests added in oc-chef-pedant in
chef/chef-server#1028 pass.
Also update the Gemfile to use HTTPS URLs for Git sources, remove unused
comments, and use the Chef Gem from RubyGems as the previous comment
suggested.

Handle the start and rows parameters correctly

---

lib/chef_zero/solr/query/unary_operator.rb
lib/chef_zero/solr/solr_parser.rb

support ! in searches

---

lib/chef_zero/chef_data/default_creator.rb

Due to a bug in oc-chef-pedant[1], we'd never noticed that this doesn't
return what it should return to match chef-server.
[1]: https://github.com/chef/chef-server/pull/1145

fix hardcoded default acls to match chef-server

---

.travis.yml
lib/chef_zero/endpoints/node_endpoint.rb
lib/chef_zero/rest_base.rb
spec/run_oc_pedant.rb

This is a first stab at implementing rfc090 (HTTP HEAD) support.
For right now, it only covers the named nodes endpoint ('/nodes/NAME').  However, it can easily be added to other endpoints as needed.
Signed-off-by: Jeremy J. Miller <jm@chef.io>

implement rfc090 for named nodes endpoint

---

lib/chef_zero/endpoints/actors_endpoint.rb

_PR against `master`_ version of #265.

GET /users?email=ME@MINE.COM -- compare emails ignoring case

---

lib/chef_zero/endpoints/cookbooks_base.rb
lib/chef_zero/endpoints/universe_endpoint.rb
lib/chef_zero/server.rb
spec/run_oc_pedant.rb

because it makes sense for chef-zero
i need it for integration testing against berks to kill off the
uses of the berkshelf-api gem.
closes #153

add the universe endpoint

---

lib/chef_zero/endpoints/cookbook_artifact_identifier_endpoint.rb

The ACLs for `cookbook_artifact` objects currently do not include the
creator of the object.  Adding the `:create` option to the `set_data`
call (which forwards it on to the `set` method on the data store),
allows the `cookbook_artifact` object to have the creator added to its
ACL.
Signed-off-by: Nolan Davidson <ndavidson@chef.io>

Fix default perms on cookbook_artifact objects

---

lib/chef_zero/chef_data/cookbook_data.rb

I'm seeing some warnings coming from Hashie, but the issue for me seems to be overriding `Mash.zip`. Here's the upstream issue: https://github.com/intridea/hashie/issues/423 and [hashie's response for disabling warnings](https://github.com/intridea/hashie/pull/395). 
The [`github` gem does this same fix](https://github.com/piotrmurach/github/blob/master/lib/github_api/mash.rb). 
```
W, [2018-03-15T15:16:39.602423 #24086]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#zip defined in Enumerable. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.
```

Disable Hashie method override warns

---

.travis.yml
Gemfile

lets us inject master of chef/chef from the chef/chef project.

remove the explicit chef gem

---

Gemfile

have a default chef gem pin for dep sanity.

reinstate the default chef gem pin

---

bin/chef-zero
lib/chef_zero/dist.rb
lib/chef_zero/endpoints/controls_endpoint.rb
lib/chef_zero/endpoints/version_endpoint.rb
lib/chef_zero/rspec.rb
lib/chef_zero/server.rb
lib/chef_zero/socketless_server_map.rb

Related to chef/chef's [#8376](https://github.com/chef/chef/issues/8376) design proposal to set brands in a single location for easy patching by community distributions.
- Add a dist.rb file defining the PRODUCT and CLIENT constants to be used in outputs.
- Replace occurences of chef-zero and Chef-Zero by their constant counterparts.
- add a require "chef_zero/dist.rb" to files updated on point above

Add ChefZero::Dist to abstract branding details to a single location

---

spec/run_oc_pedant.rb

Signed-off-by: jan shahid shaik <jashaik@progress.com>
Chef-zero is for testing against a "real" Chef Server without mocking the entire Internet.
This pedant test is to verify the openresty tags in the nginx default error responses, chef-zero is just mock the chef-server not nginx component So we are skipping this test for now.
Skipping the test

Skipping nginx default error response verification pedant test

---

lib/chef_zero/endpoints/policy_revision_endpoint.rb

Signed-off-by: Vinay Satish <vinay.satish@progress.com>
The API - `/organizations/[organization_id]/policies/[policy_name/revisions/[revision_id]` was updated in the Chef Infra Server to include `policy_group_list` in its response. Even the pedant tests were updated as part of this change.
This PR has the same changes in chef-zero to keep the APIs consistent between Chef Infra Server and chef zero.
https://github.com/chef/chef-server/pull/2818
https://github.com/chef/chef-server/issues/2867

Updating the policy_revision_endpoint to add policy_group_list

---

.expeditor/verify.pipeline.yml
.github/CODEOWNERS
chef-zero.gemspec

Signed-off-by: jayashri garud <jgarud@msystechnologies.com>

add ruby 3.0 and 3.1 tests in verify pipeline

---

.expeditor/verify.pipeline.yml
chef-zero.gemspec

Tests are broken, and making it work again doesn't have a lot of benefit.

Remove Ruby 2.6 support

---

lib/chef_zero/endpoints/sandboxes_endpoint.rb

This endpoint does N number of checksum checks, which can be really expensive when the N is large on the available server checksums and/or the client checksum requests

[SandboxesEndpoint#put] Move checksum discovery out of loop

---

.expeditor/verify.pipeline.yml
chef-zero.gemspec

This PR removes tests for version 2.7 in the verify pipeline.

ci: drop support for 2.7 tests on verify pipeline

---

.expeditor/verify.pipeline.yml
Gemfile
chef-zero.gemspec
lib/chef_zero/server.rb

Rack has a CVE. Updating to 3.1.10 to get past that. https://nvd.nist.gov/vuln/detail/CVE-2024-26141
Around v3 of 'rack', the Handler method (along with others) was split off into a new gem called 'rackup'. We included that here.

Updating rack
