chef/chef-zero

Gemfile, spec/run_pedant.rb
Update the Gemfile to use a version of Chef that allows Chef Zero 4.0
=> Use a Chef version compatible with chef-zero 4.x

CHANGELOG.md, lib/chef_zero/endpoints/version_endpoint.rb, lib/chef_zero/rest_base.rb, lib/chef_zero/server.rb, spec/server_spec.rb
/version is a stripped down version of what you get with EC/CS/OSC. Useful for knowing what you are talking to.
=> Support /version; fix some global URIs

lib/chef_zero/rspec.rb
- :organization => 'org' lets you specify that an org should be created and pointed at
- :data_scope => :context lets you specify that the server and any data should be kept around for the entire example group
=> Add :organization and :data_scope options to with_chef_server

Gemfile, lib/chef_zero/chef_data/data_normalizer.rb
=> Translate admin="true" to admin=true

chef-zero.gemspec
=> Add gemspec files to allow bundler to run from the gem

Gemfile, chef-zero.gemspec, lib/chef_zero/endpoints/dummy_endpoint.rb, lib/chef_zero/endpoints/node_endpoint.rb, lib/chef_zero/endpoints/nodes_endpoint.rb, lib/chef_zero/endpoints/organization_policies_endpoint.rb, lib/chef_zero/endpoints/organization_policy_groups_endpoint.rb, lib/chef_zero/rest_base.rb, lib/chef_zero/server.rb, spec/run_oc_pedant.rb
There's some refactoring that's possible, but this is ready for review.
=> Implement the /policies and /policy_groups API routes

.travis.yml, spec/run_oc_pedant.rb
Replaces https://github.com/chef/chef-zero/pull/188 which github won't let me re-open.
=> Enable knife pedant tests

lib/chef_zero/endpoints/actor_keys_endpoint.rb, lib/chef_zero/endpoints/organization_user_default_key_endpoint.rb, lib/chef_zero/endpoints/organization_user_key_endpoint.rb, lib/chef_zero/endpoints/organization_user_keys_endpoint.rb, lib/chef_zero/rest_request.rb, lib/chef_zero/server.rb
Keeps chef-zero in line with https://github.com/chef/chef-server/pull/769. Don't merge until other PR has the thumbsups it needs but please review.
=> Implemented GET /orgs/ORG/users/USER/keys(/key) endpoint recently added to server.

lib/chef_zero/endpoints/actor_endpoint.rb
under /organizations (otherwise ChefFS will not understand it)
=> Fix users endpoint in OSC compat mode to use a data store URL

CHANGELOG.md, lib/chef_zero/version.rb
=> Release 4.7.0

lib/chef_zero/server.rb, spec/server_spec.rb
=> Increase WEBrick request timeout to 300 seconds. Fixes #137

README.md
=> Format readme, remove waffle badges, add license

lib/chef_zero/chef_data/cookbook_data.rb
Fixes #161
cc @chef/client-core
=> Load libraries recursively

playground/.chef/knife.rb
=> Connect to chef zero default port in the playground

lib/chef_zero/endpoints/cookbook_version_endpoint.rb, spec/run_oc_pedant.rb
=> Enable policy, cookbook artifacts and ACL pedant tests

.travis.yml
=> test ruby 2.2 and 2.3

lib/chef_zero/endpoints/search_endpoint.rb
This builds on fixes added in #247 and additional tests added in
chef/chef-server#1028.
Handle the query parameters in the search method instead of the get
method to make them more consistent and work properly when start values
are given.
=> Fix pagination with start parameters

lib/chef_zero/chef_data/cookbook_data.rb
chef-zero testing is entirely aimed at chef-pedant testing of the external API and doesn't have a useful unit testing framework and i don't have the time right now to build one.
=> favor metadata.json over metadata.rb

lib/chef_zero/chef_data/cookbook_data.rb
Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>
=> change require per hashie author

Gemfile, spec/run_oc_pedant.rb
Signed-off-by: Steven Danna <steve@chef.io>
=> Remove veil dependency

spec/run_oc_pedant.rb
Signed-off-by: Thom May <thom@chef.io>
=> Ensure that we create the keys pedant needs

spec/run_oc_pedant.rb
=> Revert "Ensure that we create the keys pedant needs"

Gemfile
Signed-off-by: Thom May <thom@may.lt>
=> Ensure that tests that use chef-zero git will work

spec/run_oc_pedant.rb
as the user acls are not currently supported here
Related to https://github.com/chef/chef-server/pull/1242
Signed-off-by: Jaymala Sinha <jsinha@chef.io>
Needed to base this off 5-stable branch.
=> Add skip-chef-zero-quirks to the defaults in chef-zero

Gemfile
Needed to get chef/chef-server#1285 off the ground
=> Update gemfile dependencies

CHANGELOG.md
=> Update the changelog for 13.1

lib/chef_zero/chef_data/default_creator.rb, lib/chef_zero/data_store/memory_store_v2.rb, lib/chef_zero/data_store/raw_file_store.rb, lib/chef_zero/rest_base.rb
Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>
=> fix for new rubocop engine

.expeditor/config.yml
=> Fix deprecated config options in expeditor

chef-zero.gemspec
Update the homepage instead to get the users to our git repo
=> Don't ship the readme in the gem

chef-zero.gemspec
=> Require Rack 2.0.6 or later to resolve CVEs

.expeditor/config.yml, .rubocop.yml, .travis.yml, chef-zero.gemspec, lib/chef_zero/chef_data/default_creator.rb, lib/chef_zero/endpoints/cookbook_artifacts_endpoint.rb, lib/chef_zero/endpoints/cookbooks_base.rb
1 change per PR. A few misc things while I was in here loosening the dep on mixlib-log.
=> Loosen the mixlib-log depedency + misc cleanup

.expeditor/config.yml, .expeditor/run_linux_tests.sh, .expeditor/verify.pipeline.yml, .rspec, Gemfile, Rakefile
=> Move testing to Buildkite

Gemfile, README.md, Rakefile, chef-zero.gemspec
=> Use Chefstyle gem and move dev deps to the Gemfile

lib/chef_zero/chef_data/data_normalizer.rb
Signed-off-by: antima-gupta <agupta@msystechnologies.com>
- Added display_name in the normalize_user to fix `oc-chef-pedent` user_spec failure
[#2080](https://github.com/chef/chef-server/issues/2080)
[#2112](https://github.com/chef/chef-server/pull/2112)
=> Added display_name in the normalize_user.

README.md, spec/run_oc_pedant.rb
The status endpoint was removed.
=> Remove --skip-status from pedant

.expeditor/run_windows_tests.ps1, .expeditor/verify.pipeline.yml
Signed-off-by: skeshari12 <skeshari@msystechnologies.com>
=> Add ruby 3.0/3.1 windows tests
